# Non-sensitive global defaults
interval_seconds: 60
connection_timeout: 10
tele_workers: 3
log_file: "bot.log"
health_port: 8080
max_concurrent_checks: 50
min_interval_seconds: 20

# CPU benchmark defaults
cpu_benchmark:
  enabled: true
  url: "https://proton.saltant.io/Services?handler=CpuBenchmark&dataRange=0&networkType=2"
  threshold_seconds: 0.35
  poll_interval_seconds: 300